### ISSUE TITLE
panic when create RandWindow()

### ISSUE THREAD

**Issue by harryge00** [influxdata/influxdb-comparisons#7]
in https://github.com/influxdata/influxdb-comparisons/blob/master/bulk_query_gen/time_interval.go#L30:

```
upper := ti.End.Add(-window).UnixNano()
if upper <= lower {
        panic("logic error: bad time bounds")
    }
```

Will cause problem when start and end time are `2016-01-01 00:00:00 +0000 UTC 2016-01-01 06:00:00 +0000 UTC`, but window is 12 hours.

```
./bulk_query_gen --debug=0 --seed=321 --format=influx-http --query-type=single-host

using random seed 321
panic: logic error: bad time bounds

goroutine 1 [running]:
panic(0x5590a0, 0xc820078920)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*TimeInterval).RandWindow(0xc8200734d0, 0x274a48a78000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/pao/caicloud/influxdb-comparisons/bulk_query_gen/time_interval.go:33 +0x1df
main.(*InfluxDevops).maxCPUUsageHourByMinuteNHosts(0xc8200734c0, 0x7f6417b41560, 0xc8200b6400, 0x1, 0x1)
    /home/pao/caicloud/influxdb-comparisons/bulk_query_gen/influx_devops_common.go:66 +0x6d
main.(*InfluxDevops).MaxCPUUsageHourByMinuteOneHost(0xc8200734c0, 0x7f6417b41560, 0xc8200b6400, 0x1)
    /home/pao/caicloud/influxdb-comparisons/bulk_query_gen/influx_devops_common.go:40 +0x89
main.(*InfluxDevopsSingleHost).Dispatch(0xc8200734c0, 0x0, 0x1, 0x0, 0x0)
    /home/pao/caicloud/influxdb-comparisons/bulk_query_gen/influx_devops_singlehost.go:19 +0x84
main.main()
    /home/pao/caicloud/influxdb-comparisons/bulk_query_gen/main.go:156 +0x3e4
```

**Comment by rw** [comment]
Hi, this is just due to the default CLI options. As you pointed out, the solution is to increase the end time. I'll update the defaults so that it works out of the box.

**Comment by vlastahajek** [comment]
Enhanced validation of input params
